### DISCUSSION TITLE
Sandbox Config Tool v0

### DISCUSSION THREAD

**Discussion by kevinlu1248** [sweepai/sweep#1514] [Announcements]
This CLI tool tests your `sweep.yaml` configuration, to make the sandbox configurations easier to set up.

### Config setup
To get started, go to your local clone of your repo. Then, create your `sweep.yaml` if it doesn't already exist with `touch sweep.yaml` then set up the sandbox section of your `sweep.yaml`.

For example, for Sweep, which is Python-based, we have the following sandbox config:

```yml
sandbox:
  install:
    - apt install python3.11 -y
    - pip install poetry
    - poetry env use python3.11
    - poetry install
  check: 
    - poetry run pylint --errors-only {file_path}
```

And for our landing page, which is Typescript-based, we have the following config

```yml
sandbox:
  install:
    - "yarn install --ignore-engines"
  check:
    - "yarn run prettier --write {file_path}"
    - "yarn run eslint {file_path}"
    - "yarn run tsc"
```

By default, we use the following Trunk-based config

```yml
sandbox:
  install:
    - trunk init
  check:
    - trunk fmt {file_path}
    - trunk check {file_path}
```

We recommend starting with the formatters 

### Testing
You can test the install and check flows of your `sweep.yaml` by executing the `sweep-sandbox` binary from the base of your repo in the following format:

```sh
sweep-sandbox {file_path}
```

For example in the Sweep repo, we run `sweep-sandbox sweepai` to test it on the entire repo and `sweep-sandbox sweepai/api.py`.

<hr /><em>This discussion was created from the release <a href='https://github.com/sweepai/sweep/releases/tag/'>Sandbox Config Tool v0</a>.</em>
