### ISSUE TITLE
Sweep: feature request: option to persist deeplake embeddings on a docker compose volume 

### ISSUE THREAD

**Issue by vermaat** [sweepai/sweep#2292]
### Details

feature request: option to persist deeplake embeddings on a docker compose volume.

Current situation: the Deeplake database is started and stored in memory. Everytime the docker-compose project is reloaded a new deeplake database is created in `vector_db.py` using the following code:

```
def init_deeplake_vs(repo_name):
    deeplake_repo_path = f"mem://{int(time.time())}{repo_name}"
    deeplake_vector_store = VectorStore(
        path=deeplake_repo_path, read_only=False, overwrite=False
    )
    return deeplake_vector_store
```

The docker-compose file also does not persist the data:
```
version: '2'
services:
  webhook:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    image: sweepai/sweep
    volumes:
      - .:/app
      - /sweep_docs:/sweep_docs
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    command: >
      sh -c "echo PORT: ${PORT:-8080} && . bin/startup.sh"
    stdin_open: true
    tty: true
    links:
      - sandbox-web
    environment:
      - PORT=${PORT:-8080}
  sandbox:
    env_file:
      - .env
    build:
      context: sweepai/sandbox
      dockerfile: Dockerfile.sandbox
    image: sweepai/sandbox
    scale: 0
  sandbox-web:
    env_file:
      - .env
    build:
      context: sweepai/sandbox
      dockerfile: Dockerfile.web
    image: sweepai/sandbox-web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080
```

Please add this feature or explain how to do this using the existing repository. This is useful with the self hosted sweep version to debug and try things fast without having to embedded items over and over again.
