### ISSUE TITLE
Sweep: Github actions always fail

### ISSUE THREAD

**Issue by ztxtz** [sweepai/sweep#982]
### Details

Sweeper is incorrectly parsing the output of Github actions. It treats all of the following output as an error even though the status of the Github action is green (passing). By treaing all output as failing, the sweeper is entirely useless since it cannot self-correct using test output.

**Example 1:**

```
##[group]Starting postgres service container
##[command]/usr/bin/docker pull postgres:11-alpine
11-alpine: Pulling from library/postgres
...
Digest: sha256:abed8d4c6fd728512f8b44d8ed9c2bcf624fd5523126c7e6df577fd4c60beb74
Status: Downloaded newer image for postgres:11-alpine
docker.io/library/postgres:11-alpine
##[command]/usr/bin/docker create --name d2d27b24a9a24793be633079bb87ab0c_postgres11alpine_a7e53f --label 5bedb4 --network github_network_f639688371834017b2c432dc5d3fc607 --network-alias postgres -p 5432:5432  -e "POSTGRES_DB=rails_test" -e "POSTGRES_USER=rails" -e "POSTGRES_PASSWORD=password" -e GITHUB_ACTIONS=true -e CI=true postgres:11-alpine
94738d77c422bf6b5d4528214853b738d9122a8f9648a2c4d2864c62e1800a89
##[command]/usr/bin/docker start 94738d77c422bf6b5d4528214853b738d9122a8f9648a2c4d2864c62e1800a89
94738d77c422bf6b5d4528214853b738d9122a8f9648a2c4d2864c62e1800a89
##[command]/usr/bin/docker ps --all --filter id=94738d77c422bf6b5d4528214853b738d9122a8f9648a2c4d2864c62e1800a89 --filter status=running --no-trunc --format "{{.ID}} {{.Status}}"
94738d77c422bf6b5d4528214853b738d9122a8f9648a2c4d2864c62e1800a89 Up Less than a second
##[command]/usr/bin/docker port 94738d77c422bf6b5d4528214853b738d9122a8f9648a2c4d2864c62e1800a89
5432/tcp -> 0.0.0.0:5432
5432/tcp -> [::]:5432
##[endgroup]
```

**Example 2:**

```
##[group]Run actions/setup-node@v2
with:
node-version: 14
always-auth: false
check-latest: false
token: ***
##[endgroup]
Found in cache @ /opt/hostedtoolcache/node/14.21.3/x64
Post job cleanup.
Post job cleanup.
git version 2.41.0
Temporarily overriding HOME='/home/runner/work/_temp/9c9ad263-3ecf-4ced-b733-7af32de7881b' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
http.https://github.com/.extraheader
Cleaning up orphan processes
```

**Example 3:**

```
##[group]Run bundle exec brakeman -q -w2
�[36;1mbundle exec brakeman -q -w2�[0m
shell: /usr/bin/bash -e {0}
##[endgroup]

== Brakeman Report ==

Application Path: /home/runner/work/reponame/reponame
Rails Version: 7.0.6
Brakeman Version: 6.0.1
Scan Date: 2023-08-05 08:40:54 +0000
Duration: 0.820110136 seconds
Checks Run: BasicAuth, BasicAuthTimingAttack, CSRFTokenForgeryCVE, ContentTag, CookieSerialization, CreateWith, CrossSiteScripting, DefaultRoutes, Deserialize, DetailedExceptions, DigestDoS, DynamicFinders, EOLRails, EOLRuby, EscapeFunction, Evaluation, Execute, FileAccess, FileDisclosure, FilterSkipping, ForgerySetting, HeaderDoS, I18nXSS, JRubyXML, JSONEncoding, JSONEntityEscape, JSONParsing, LinkTo, LinkToHref, MailTo, MassAssignment, MimeTypeDoS, ModelAttrAccessible, ModelAttributes, ModelSerialize, NestedAttributes, NestedAttributesBypass, NumberToCurrency, PageCachingCVE, Pathname, PermitAttributes, QuoteTableName, Redirect, RegexDoS, Render, RenderDoS, RenderInline, ResponseSplitting, RouteDoS, SQL, SQLCVEs, SSLVerify, SafeBufferManipulation, SanitizeConfigCve, SanitizeMethods, SelectTag, SelectVulnerability, Send, SendFile, SessionManipulation, SessionSettings, SimpleFormat, SingleQuotes, SkipBeforeFilter, SprocketsPathTraversal, StripTags, SymbolDoSCVE, TemplateInjection, TranslateBug, UnsafeReflection, UnsafeReflectionMethods, ValidationRegex, VerbConfusion, WeakRSAKey, WithoutProtection, XMLDoS, YAMLParsing

== Overview ==

Controllers: 4
Models: 1
Templates: 6
Errors: 0
Security Warnings: 0

== Warning Types ==


No warnings found
```

**workflow.yml**

```
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Install Node.js and npm packages
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bin/rake


```

### Suggested solution:

If the status of the Github action is green (passing), we should not be checking the output at all and it should always be treated as passing.

If the status of a Github action is red (failing), fetch the log and improve parsing to detect what is just a notice and what is an actual error.
